server:
  port: 8762
spring:
  application:
    name: eureka-server2
  security:
    user:
      name: zhuweiwei1
      password: zhuweiwei1
      roles: SERVICE_NODE
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://zhuweiwei:zhuweiwei@server1:8761/eureka
  instance:
    hostname: server2