server:
  port: 8010
spring:
  application:
    name: eureka-provider
  datasource:
    username: root
    password: manager
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 10
      max-wait-millis: 500
      max-idle: 20
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true #当前服务信息访问路径显示ip
    instance-id: ${eureka.instance.ip-address}:${server.port}:${spring.application.name}