server:
  port: 8002
  servlet:
    context-path: /eurekaProvider
spring:
  application:
    name: eureka-provider
  datasource:
    username: root
    password: manager
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      max-wait-millis: 200
      max-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://zhuweiwei:zhuweiwei@server1:8761/eureka/
  #      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    ip-address: 192.168.1.117
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}:V1.0
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: assign_id
