server:
  port: 8761
spring:
  application:
    name: eureka-server1
  security:
    user:
      name: zhuweiwei
      password: zhuweiwei
      roles: SERVICE_NODE
eureka:
  instance:
    hostname: server1
    instance-id: ${eureka.instance.hostname}:${server.port}:V1.0
  client:
    healthcheck:
      enabled: false
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://zhuweiwei1:zhuweiwei1@server2:8762/eureka/