server:
  port: 8003
spring:
  application:
    name: eureka-consumer
eureka:
  client:
    service-url:
      defaultZone: http://zhuweiwei1:zhuweiwei1@server2:8762/eureka/
  instance:
    ip-address: 192.168.1.117
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}:V1.0
#      defaultZone: http://127.0.0.1:8761/eureka/
