server:
  servlet:
    context-path: /eurekaProvider
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: assign_id
#当前服务介绍信息
info:
  groupId: @groupId@
  artifactId: @artifactId@
  version: @version@
  name: @name@
  description: @description@