server:
  port: 8001
  servlet:
    context-path: /eurekaProvider
spring:
  application:
    name: EUREKA-PROVIDER
  datasource:
    username: root
    password: manager
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      max-wait-millis: 200
      max-idle: 10
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: assign_id
eureka:
  client:
    service-url:
      defaultZone: http://zhuweiwei:zhuweiwei@server1:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true #当前服务信息访问路径显示ip
    instance-id: ${eureka.instance.ip-address}:${server.port}:${spring.application.name}:@springcloud.demo.project.version@
#当前服务介绍信息
info:
  groupId: @groupId@
  artifactId: @artifactId@
  version: @version@
  name: @name@
  description: @description@
