server:
  port: 8761
spring:
  application:
    name: eureka-server1
  security:
    user:
      name: zhuweiwei
      password: zhuweiwei
      roles: SERVICE_NODE
eureka:
  #关闭自我保护机制
  #  server:
  #    enable-self-preservation: false
  client:
    fetch-registry: false # 作为注册中心只维护其它微服务节点实例，不去检索服务
    register-with-eureka: false #自己不向注册中心注册
    service-url:
      defaultZone: http://zhuweiwei1:zhuweiwei1@server2:8762/eureka/
  instance:
    hostname: server1
