server:
  port: 8003
  servlet:
    context-path: /eurekaFeign
spring:
  application:
    name: eureka-feign
eureka:
  client:
    service-url:
      defaultZone: http://zhuweiwei:zhuweiwei@server1:8761/eureka/
  instance:
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}:${spring.application.name}:@springcloud.demo.project.version@
    prefer-ip-address: true
#当前服务介绍信息
info:
  groupId: @groupId@
  artifactId: @artifactId@
  version: @version@
  name: @name@
  description: @description@
ribbon:
  eager-load:
    enabled: true